// apps/electron-app/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { Button, Input } from "@muxiao-fek-base/ui";
import { createI18n } from "@muxiao-fek-base/i18n";

const i18n = createI18n({
  baseLocale: "zh-CN",
});

const message = ref("");

function handleSubmit() {
  alert(i18n.t("common_submit") + ": " + message.value);
}
</script>

<template>
  <div class="app">
    <h1>Electron App - {{ i18n.t("common_submit") }}</h1>
    <Input v-model="message" :placeholder="i18n.t('common_search')" />
    <Button type="primary" @click="handleSubmit">
      {{ i18n.t("common_submit") }}
    </Button>
  </div>
</template>

<style scoped>
.app {
  padding: 24px;
}
</style>

// apps/react-app/src/App.tsx
import { useState } from "react";
import { createI18n } from "@muxiao-fek-base/i18n";

const i18n = createI18n({
  baseLocale: "zh-CN",
});

export default function App() {
  const [message, setMessage] = useState("");

  const handleSubmit = () => {
    alert(i18n.t("common_submit") + ": " + message);
  };

  return (
    <div style={{ padding: "24px" }}>
      <h1>{i18n.t("common_submit")}</h1>
      <input
        type="text"
        value={message}
        onChange={(e) => setMessage(e.target.value)}
        placeholder={i18n.t("common_search")}
      />
      <button onClick={handleSubmit}>{i18n.t("common_submit")}</button>
    </div>
  );
}
